kind: ConfigMap
apiVersion: v1
metadata:
  name: kharvest-client
  namespace: default
  labels:
    demo: kharvest
data:
  kharvest.cfg: |-
    /cfg/cmkharvest/file1
    /cfg/cmkharvest/file2
    /cfg/cmkharvest/file3